apiVersion: template.openshift.io/v1
kind: Template
objects:
  # Gitlab Secret
  - kind: Secret
    apiVersion: v1
    metadata:
      name: sfdc-${env}-secret
      annotations:
        paas.redhat.com/encrypted: 'true'
    data:
      PASSWORD: ${PASSWORD}
      TOKEN: ${TOKEN}
      USERNAME: ${USERNAME}
    type: Opaque

parameters:
- name: env
  description: ENV
  required: true
- name: PASSWORD
  description: PASSWORD
  required: true
- name: TOKEN
  description: TOKEN
  required: true
- name: USERNAME
  description: USERNAME
  required: true